---
abstract: 'Swim Badge Image Support'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Swim-Plugin-badge
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  Swim: v0.1.33
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/swim-plugin-badge-pm/issues
  homepage: https://github.com/ingydotnet/swim-plugin-badge-pm
  repository: https://github.com/ingydotnet/swim-plugin-badge-pm.git
version: 0.1.8
